name: Health check

on:
  # Run daily at 9:00 AM UTC
  schedule:
    - cron: '0 9 * * *'

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright browsers
        run: uv run playwright install chromium --with-deps

      - name: Run health check
        run: uv run python run_health_check.py --save-report

      - name: Upload health check report
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if health check fails
        with:
          name: health-check-report-${{ github.run_number }}
          path: data/health_check_report.json
          retention-days: 30
